[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Serialisable SocketAddr"
documentation = "http://maidsafe.net/socket_addr/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "socket_addr"
readme = "README.md"
repository = "https://github.com/maidsafe/socket_addr"
version = "0.0.3"

[dependencies]
clippy = {version = "~0.0.44", optional = true}
rustc-serialize = "~0.3.18"
